#!/usr/bin/env bash
set -e

cleanup() {
    exec 3>&-
	rm "$FIFO_UEBERZUG"
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	/opt/lf/lf $@
else
	export FIFO_UEBERZUG="/tmp/lf-ueberzug-$$"
	mkfifo "$FIFO_UEBERZUG"
	ueberzug layer -s <"$FIFO_UEBERZUG" -p bash &
	exec 3>"$FIFO_UEBERZUG"
	trap cleanup EXIT
	/opt/lf/lf "$@" 3>&-
fi
