#!/usr/bin/sh
start_ueberzug() {
	[ -p "$FIFO_UEBERZUG" ] || mkfifo "$FIFO_UEBERZUG" && chmod 666 "$FIFO_UEBERZUG" || exit 1
	ueberzug layer --parser simple --silent < "$FIFO_UEBERZUG" &
	upid="$!"
	exec 3>"$FIFO_UEBERZUG"
}

stop_ueberzug() {
	exec 3>&-
	kill $upid
}

if [ -n "$DISPLAY" ] && command -v ueberzug 2>&1 > /dev/null; then
    export FIFO_UEBERZUG="/tmp/lf-ueberzugfifo-$USER"
    trap stop_ueberzug EXIT QUIT INT TERM
    start_ueberzug
fi
/opt/lf/lf "$@"
